kind: ImageStream
apiVersion: image.openshift.io/v1
metadata:
  name: html-openshift-app
  labels:
    app: html-openshift-app
    app.kubernetes.io/part-of: html-openshift-app
spec:
  lookupPolicy:
    local: false